function [A,ATKA,X,total_t]=RAKDL(train,Tdata,iter,dict_size,c_ratio,k,kernel_choice, kervar1, kervar2,tol_bcg,itnlim)
% ========================================================================
% Author: Jiali Yang (yjiali2015@163.com)
% Date: 08-04-2024
% Gang Wu, Jiali Yang, Randomized Algorithms for Large-Scale Dictionary Learning, Submitted to Netural Networks.
% Algorithm 6: A Randomized algorithm for kernel dictionary learning
% Input:
%   train---training set, 
%   Tdata--- sparsity level, 
%   iter---Number of iterations of the main loop, 
%   dict_size---number of atoms,
%   c_ratio---Sampling rate of the Nystrom approximation of the kernel matrix, 
%   k---Target rank for low-rank approximation of KA, 
%   kernel_choice---Kernel function type,
%   kervar1, kervar2---Arguments to the kernel function, 
%   tol_bcg---Convergence threshold for blockcg1
%   itnlim---Number of iterations for blockcg1
% Output:
%    A---Dictionary matrix obtained from kernel DL algorithm
%    ATKA---The approximation of A'*K*A
%    X---Sparse representation matrix
%    total_t---computation time
% ========================================================================

total_tic = tic;
ker_params.ker_type=kernel_choice;
ker_params.ker_param_1= kervar1;
ker_params.ker_param_2= kervar2;
P=k+20; %oversampling 20
N=size(train,2);
A = zeros(N, dict_size) ;

%===========================
%Step 1: Nystrom approximation of the kernel matrix
permute_vec = randperm(size(train,2));
c=round(c_ratio*size(train,2)); 
supp = permute_vec(1:c);
Y = train(:,supp); % subsample of training
ker_params.X = train;
ker_params.Y = Y;  
C = calc_kernel(train'*Y,ker_params);  %Compute the kernel matrix C
ker_params.X = Y;
W = calc_kernel(Y'*Y,ker_params);  %Compute the kernel matrix W
W=max(W,W');
[V_w,D_w] = eig(W);  
W_pinv=V_w*pinv(D_w)*V_w';  

%===========================
%Step 2: Inverse the kernel matrix 
 [Q_c,R_c]=qr(C,0);
 [Uw,Sw,~] = svd(R_c*W_pinv*R_c');  %pinv(K)=(Q_c*Uw)*pinv(Sw)*(Q_c*Uw)'

%===========================
%Step 3: Initialize the dictionary matrix A and compute the initial sparse matrix X     
randid = randperm(size(train,2));
for j=1:dict_size
    A(randid(j),j) = 1;  %initial dictionary
end
ATK=(A'*C*W_pinv)*C';
ATKA=ATK*A;
sigma=diag(ATKA);  
ATKA=ATKA./repmat(sigma,[1,size(A,2)]); 
ATK=ATK./repmat(sigma,[1,size(train,2)]);  
X = omp(ATK,ATKA,Tdata) ;

%===========================
%Step 4: The main loop
for i=1:iter
    Omgc=randn(size(X,1),P);       
    Q = blockcg1(X,Omgc,tol_bcg,itnlim);
    Q=C*W_pinv*((C'*X')*Q);
    [Q,~]=qr(Q,0);     
    ST = blockcg1(X,X*C,tol_bcg,itnlim);
    ST=(Q'*C*W_pinv)*ST';           
    [U1,S1,V1]=svd(ST,'econ');      
    U1= Q*U1;
    U= U1(:, 1:k);
    S =sparse(S1(1:k,1:k));
    V= V1(:, 1:k);                 
    ATK=V*S*U';
    
%===========================
%By the low-rank approximation of KA to compute A
    A=(Q_c*Uw)*(pinv(Sw)*(Q_c*Uw)'*ATK');

%=========================================
%Calculating X from ATK and A
     ATKA=ATK*A;   %Theoretically symmetrical     
     sigma=diag(ATKA);  %The column vector generated by the diagonal elements, which cannot appear 0
     sigma=sqrt(abs(sigma));
     ATK=ATK./repmat(sigma,[1,size(train,2)]);   
     A=A./repmat(sigma',[size(train,2),1]);      
     sigma=sigma*sigma';
     ATKA=ATKA./sigma; % normalize to norm-1 in feature space
      
     X = omp(ATK,ATKA,Tdata) ;
       
end

total_t = toc(total_tic);
end